import = [
    "~/.config/alacritty/themes/themes/tokio-night.toml"
]

[ env ]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

decorations = "Buttonless"

[font]
normal.family = "JetBrains Mono Nerd Font"
normal.style = "Regular"

#regular
size = 12

#for video
# size = 35.0
